AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
    - "_site/**/*"
    - "assets/history/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - 'https?://'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
