title: Phalanx | Open Tactical Card System
description: Phalanx is an open tactical card system and suite of game formats designed for deep strategy and accessibility.
url: https://phalanxduel.com
baseurl: ""
permalink: pretty
markdown: kramdown
game_url: https://play.phalanxduel.com
kramdown:
  input: GFM
defaults:
  - scope:
      path: ""
    values:
      layout: default
