project_name: "phx-site"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Done"]
labels: []
definition_of_done: ["The a11y is run agains the site and all claims are verified against the official rules and guidlines for Phalanx Duel"]
date_format: yyyy-mm-dd
max_column_width: 20
default_editor: "/opt/homebrew/bin/nvim"
auto_open_browser: true
default_port: 6423
remote_operations: true
auto_commit: true
zero_padded_ids: 3
bypass_git_hooks: true
check_active_branches: true
active_branch_days: 30
task_prefix: "task"
